const CET6_WORDS = [
{"word":"abandoned","meaning":"(adj.) 被抛弃的；废弃的"},
{"word":"abruptly","meaning":"(adv.) 突然地；唐突地"},
{"word":"abstract","meaning":"(adj.) 抽象的；(v.) 提取"},
{"word":"abundance","meaning":"(n.) 丰富；充裕"},
{"word":"access","meaning":"(n.) 通道；机会 (v.) 接近"},
{"word":"accessories","meaning":"(n.) 配件；附件"},
{"word":"accommodate","meaning":"(v.) 容纳；适应；提供住宿"},
{"word":"accomplished","meaning":"(adj.) 有造诣的；完成的"},
{"word":"accomplishing","meaning":"(v.) 完成；实现"},
{"word":"accountable","meaning":"(adj.) 负有责任的；可解释的"},
{"word":"accumulate","meaning":"(v.) 积累；堆积"},
{"word":"accurate","meaning":"(adj.) 准确的；精确的"},
{"word":"accustomed","meaning":"(adj.) 习惯的；适应的"},
{"word":"acknowledge","meaning":"(v.) 承认；致谢"},
{"word":"acquired","meaning":"(adj.) 获得的；习得的"},
{"word":"adapt","meaning":"(v.) 适应；改编"},
{"word":"adequate","meaning":"(adj.) 充足的；适当的"},
{"word":"adhere","meaning":"(v.) 坚持；黏附"},
{"word":"adjacent","meaning":"(adj.) 邻近的；毗连的"},
{"word":"adjusted","meaning":"(adj.) 调整过的；适应的"},
{"word":"administered","meaning":"(v.) 管理；执行"},
{"word":"admire","meaning":"(v.) 钦佩；赞赏"},
{"word":"advent","meaning":"(n.) 出现；到来"},
{"word":"adverse","meaning":"(adj.) 不利的；有害的"},
{"word":"advocates","meaning":"(v.) 提倡 (n.) 提倡者"},
{"word":"aesthetic","meaning":"(adj.) 美学的；审美的"},
{"word":"affection","meaning":"(n.) 喜爱；感情"},
{"word":"affordable","meaning":"(adj.) 负担得起的"},
{"word":"aggravate","meaning":"(v.) 加重；使恶化"},
{"word":"aggressive","meaning":"(adj.) 侵略的；好斗的"},
{"word":"agile","meaning":"(adj.) 敏捷的；灵活的"},
{"word":"alarming","meaning":"(adj.) 令人担忧的"},
{"word":"alert","meaning":"(adj.) 警觉的 (v.) 警告"},
{"word":"alien","meaning":"(adj.) 外来的；陌生的 (n.) 外星人"},
{"word":"alleviate","meaning":"(v.) 减轻；缓解"},
{"word":"alliance","meaning":"(n.) 联盟；同盟"},
{"word":"allocate","meaning":"(v.) 分配；拨出"},
{"word":"allowance","meaning":"(n.) 津贴；限额"},
{"word":"alter","meaning":"(v.) 改变；修改"},
{"word":"alternative","meaning":"(adj.) 替代的 (n.) 选择"},
{"word":"ambitious","meaning":"(adj.) 有抱负的；雄心勃勃的"},
{"word":"amend","meaning":"(v.) 修正；修改"},
{"word":"ample","meaning":"(adj.) 充足的；丰富的"},
{"word":"analyzing","meaning":"(v.) 分析"},
{"word":"ancestors","meaning":"(n.) 祖先；先驱"},
{"word":"anecdotal","meaning":"(adj.) 轶事的；传闻的"},
{"word":"animated","meaning":"(adj.) 活跃的；栩栩如生的"},
{"word":"annual","meaning":"(adj.) 年度的 (n.) 年刊"},
{"word":"anonymous","meaning":"(adj.) 匿名的；无名的"},
{"word":"anticipated","meaning":"(v.) 预期；期望"},
{"word":"anxiety","meaning":"(n.) 焦虑；不安"},
{"word":"appalling","meaning":"(adj.) 骇人的；极差的"},
{"word":"appeal","meaning":"(v.) 呼吁；吸引 (n.) 呼吁；吸引力"},
{"word":"appealing","meaning":"(adj.) 有吸引力的；恳求的"},
{"word":"appetite","meaning":"(n.) 食欲；欲望"},
{"word":"applaud","meaning":"(v.) 鼓掌；称赞"},
{"word":"application","meaning":"(n.) 应用；申请"},
{"word":"appointed","meaning":"(adj.) 指定的；被任命的"},
{"word":"appreciate","meaning":"(v.) 欣赏；感激；增值"},
{"word":"appreciation","meaning":"(n.) 欣赏；感激"},
{"word":"approach","meaning":"(v.) 接近 (n.) 方法；途径"},
{"word":"appropriate","meaning":"(adj.) 适当的；恰当的"},
{"word":"approval","meaning":"(n.) 批准；赞同"},
{"word":"approximately","meaning":"(adv.) 大约；近似地"},
{"word":"apt","meaning":"(adj.) 恰当的；易于…的"},
{"word":"arbitrary","meaning":"(adj.) 任意的；武断的"},
{"word":"archaeological","meaning":"(adj.) 考古学的"},
{"word":"arduous","meaning":"(adj.) 艰巨的；费力的"},
{"word":"arise","meaning":"(v.) 出现；产生"},
{"word":"aroused","meaning":"(v.) 唤醒；激起"},
{"word":"arrangement","meaning":"(n.) 安排；布置"},
{"word":"articulate","meaning":"(v.) 清楚地表达 (adj.) 善于表达的"},
{"word":"artificial","meaning":"(adj.) 人工的；虚假的"},
{"word":"ascend","meaning":"(v.) 上升；攀登"},
{"word":"ascertained","meaning":"(v.) 确定；查明"},
{"word":"ascribed","meaning":"(v.) 归因于"},
{"word":"aspiration","meaning":"(n.) 抱负；渴望"},
{"word":"assault","meaning":"(n./v.) 攻击；袭击"},
{"word":"assemble","meaning":"(v.) 集合；组装"},
{"word":"assert","meaning":"(v.) 断言；主张"},
{"word":"assess","meaning":"(v.) 评估；估价"},
{"word":"assigned","meaning":"(v.) 分配；指派"},
{"word":"assimilate","meaning":"(v.) 吸收；同化"},
{"word":"assistance","meaning":"(n.) 帮助；援助"},
{"word":"associated","meaning":"(adj.) 关联的；相关的"},
{"word":"assume","meaning":"(v.) 假定；承担"},
{"word":"assumption","meaning":"(n.) 假设；承担"},
{"word":"assurance","meaning":"(n.) 保证；确信"},
{"word":"astonishing","meaning":"(adj.) 令人惊讶的"},
{"word":"atmosphere","meaning":"(n.) 气氛；大气层"},
{"word":"attacked","meaning":"(v.) 攻击；抨击"},
{"word":"attain","meaning":"(v.) 达到；获得"},
{"word":"attempt","meaning":"(v./n.) 尝试；企图"},
{"word":"attribute","meaning":"(v.) 归因于 (n.) 属性；特质"},
{"word":"authentic","meaning":"(adj.) 真实的；可靠的"},
{"word":"authority","meaning":"(n.) 权威；当局"},
{"word":"autonomous","meaning":"(adj.) 自治的；自主的"},
{"word":"available","meaning":"(adj.) 可用的；可得到的"},
{"word":"avert","meaning":"(v.) 避免；转移"},
{"word":"avid","meaning":"(adj.) 热衷的；贪婪的"},
{"word":"awakened","meaning":"(v.) 唤醒；觉醒"},
{"word":"backed","meaning":"(v.) 支持；后退"},
{"word":"baffled","meaning":"(adj.) 困惑的"},
{"word":"balanced","meaning":"(adj.) 平衡的；均衡的"},
{"word":"ban","meaning":"(v./n.) 禁止；禁令"},
{"word":"bankruptcy","meaning":"(n.) 破产"},
{"word":"barely","meaning":"(adv.) 仅仅；几乎不"},
{"word":"barren","meaning":"(adj.) 贫瘠的；不育的"},
{"word":"barrier","meaning":"(n.) 障碍；屏障"},
{"word":"beneficial","meaning":"(adj.) 有益的；有利的"},
{"word":"benefit","meaning":"(n.) 利益 (v.) 有益于"},
{"word":"betray","meaning":"(v.) 背叛；泄露"},
{"word":"bizarre","meaning":"(adj.) 奇异的；古怪的"},
{"word":"blame","meaning":"(v.) 责备 (n.) 过失"},
{"word":"blatant","meaning":"(adj.) 公然的；明目张胆的"},
{"word":"bleak","meaning":"(adj.) 黯淡的；荒凉的"},
{"word":"blended","meaning":"(adj.) 混合的"},
{"word":"blessed","meaning":"(adj.) 受祝福的；幸运的"},
{"word":"bliss","meaning":"(n.) 极乐；幸福"},
{"word":"block","meaning":"(v.) 阻塞 (n.) 块；街区"},
{"word":"bloom","meaning":"(v.) 开花 (n.) 花；花期"},
{"word":"boost","meaning":"(v.) 促进；增加 (n.) 推动"},
{"word":"bound","meaning":"(adj.) 一定的；受约束的 (v.) 跳跃"},
{"word":"boundary","meaning":"(n.) 边界；界限"},
{"word":"brave","meaning":"(adj.) 勇敢的 (v.) 面对"},
{"word":"breakthrough","meaning":"(n.) 突破；重大进展"},
{"word":"breed","meaning":"(v.) 繁殖；饲养 (n.) 品种"},
{"word":"brilliant","meaning":"(adj.) 杰出的；辉煌的"},
{"word":"brink","meaning":"(n.) 边缘"},
{"word":"brisk","meaning":"(adj.) 轻快的；活跃的"},
{"word":"brittle","meaning":"(adj.) 脆的；易碎的"},
{"word":"broadcast","meaning":"(v./n.) 广播；播放"},
{"word":"budget","meaning":"(n.) 预算 (v.) 编预算"},
{"word":"burden","meaning":"(n.) 负担 (v.) 使负重"},
{"word":"bureaucratic","meaning":"(adj.) 官僚的；官僚主义的"},
{"word":"calculate","meaning":"(v.) 计算；估计"},
{"word":"campaign","meaning":"(n.) 运动；战役 (v.) 发起运动"},
{"word":"cancel","meaning":"(v.) 取消；撤销"},
{"word":"candidate","meaning":"(n.) 候选人；应试者"},
{"word":"capable","meaning":"(adj.) 有能力的"},
{"word":"capacity","meaning":"(n.) 容量；能力"},
{"word":"capture","meaning":"(v.) 捕获；夺取 (n.) 捕获"},
{"word":"catastrophe","meaning":"(n.) 灾难；大祸"},
{"word":"cater","meaning":"(v.) 迎合；提供饮食"},
{"word":"cautious","meaning":"(adj.) 谨慎的；小心的"},
{"word":"cease","meaning":"(v.) 停止；终止"},
{"word":"celebrated","meaning":"(adj.) 著名的；受人敬仰的"},
{"word":"ceremony","meaning":"(n.) 仪式；典礼"},
{"word":"certainty","meaning":"(n.) 确定性；确信"},
{"word":"challenged","meaning":"(v.) 质疑；挑战"},
{"word":"champion","meaning":"(n.) 冠军；拥护者 (v.) 支持"},
{"word":"characteristic","meaning":"(adj.) 特有的 (n.) 特征"},
{"word":"charitable","meaning":"(adj.) 慈善的；宽容的"},
{"word":"cherish","meaning":"(v.) 珍视；怀有"},
{"word":"chronic","meaning":"(adj.) 慢性的；长期的"},
{"word":"circumstance","meaning":"(n.) 环境；情况"},
{"word":"civilian","meaning":"(n.) 平民 (adj.) 民用的"},
{"word":"clash","meaning":"(v./n.) 冲突；不协调"},
{"word":"classified","meaning":"(adj.) 机密的；分类的"},
{"word":"climax","meaning":"(n.) 高潮；顶点"},
{"word":"cling","meaning":"(v.) 紧握；依恋"},
{"word":"clue","meaning":"(n.) 线索；提示"},
{"word":"clumsy","meaning":"(adj.) 笨拙的；不得体的"},
{"word":"coarse","meaning":"(adj.) 粗糙的；粗俗的"},
{"word":"coincide","meaning":"(v.) 同时发生；一致"},
{"word":"collaborate","meaning":"(v.) 合作；协作"},
{"word":"collapse","meaning":"(v./n.) 倒塌；崩溃"},
{"word":"colleague","meaning":"(n.) 同事；同僚"},
{"word":"collective","meaning":"(adj.) 集体的 (n.) 集体"},
{"word":"combat","meaning":"(v./n.) 战斗；对抗"},
{"word":"commence","meaning":"(v.) 开始；着手"},
{"word":"comment","meaning":"(n.) 评论 (v.) 发表意见"},
{"word":"commerce","meaning":"(n.) 商业；贸易"},
{"word":"commission","meaning":"(n.) 委员会；佣金 (v.) 委托"},
{"word":"commit","meaning":"(v.) 承诺；犯(罪)；投入"},
{"word":"committed","meaning":"(adj.) 坚定的；献身的"},
{"word":"commodity","meaning":"(n.) 商品；日用品"},
{"word":"communicate","meaning":"(v.) 交流；传达"},
{"word":"community","meaning":"(n.) 社区；共同体"},
{"word":"companion","meaning":"(n.) 同伴；伙伴"},
{"word":"comparable","meaning":"(adj.) 可比较的；类似的"},
{"word":"compatible","meaning":"(adj.) 兼容的；合得来的"},
{"word":"compel","meaning":"(v.) 强迫；迫使"},
{"word":"compensate","meaning":"(v.) 补偿；赔偿"},
{"word":"compete","meaning":"(v.) 竞争；比赛"},
{"word":"competent","meaning":"(adj.) 有能力的；胜任的"},
{"word":"compile","meaning":"(v.) 编译；汇编"},
{"word":"complement","meaning":"(v.) 补充 (n.) 补语"},
{"word":"complex","meaning":"(adj.) 复杂的 (n.) 综合体"},
{"word":"compliance","meaning":"(n.) 顺从；遵从"},
{"word":"complicated","meaning":"(adj.) 复杂的；难懂的"},
{"word":"compliment","meaning":"(n.) 赞美 (v.) 称赞"},
{"word":"comply","meaning":"(v.) 遵从；服从"},
{"word":"component","meaning":"(n.) 组成部分；成分"},
{"word":"compose","meaning":"(v.) 组成；创作"},
{"word":"comprehensive","meaning":"(adj.) 全面的；综合的"},
{"word":"compromise","meaning":"(v./n.) 妥协；折中"},
{"word":"compulsory","meaning":"(adj.) 强制的；义务的"},
{"word":"conceal","meaning":"(v.) 隐藏；隐瞒"},
{"word":"conceive","meaning":"(v.) 构想；怀孕"},
{"word":"concentrate","meaning":"(v.) 集中；浓缩"},
{"word":"conception","meaning":"(n.) 概念；构想"},
{"word":"concern","meaning":"(v.) 涉及；使担忧 (n.) 关心"},
{"word":"concrete","meaning":"(adj.) 具体的 (n.) 混凝土"},
{"word":"conduct","meaning":"(v.) 实施；指挥 (n.) 行为"},
{"word":"confess","meaning":"(v.) 承认；坦白"},
{"word":"confine","meaning":"(v.) 限制；禁闭"},
{"word":"confirm","meaning":"(v.) 证实；确认"},
{"word":"conflict","meaning":"(n.) 冲突；矛盾 (v.) 冲突"},
{"word":"conform","meaning":"(v.) 遵从；符合"},
{"word":"confront","meaning":"(v.) 面对；对抗"},
{"word":"confuse","meaning":"(v.) 使困惑；混淆"},
{"word":"congratulate","meaning":"(v.) 祝贺"},
{"word":"conquest","meaning":"(n.) 征服；战胜"},
{"word":"conscience","meaning":"(n.) 良心；道德感"},
{"word":"conscious","meaning":"(adj.) 有意识的；自觉的"},
{"word":"consecutive","meaning":"(adj.) 连续的；连贯的"},
{"word":"consensus","meaning":"(n.) 共识；一致意见"},
{"word":"consent","meaning":"(v./n.) 同意；准许"},
{"word":"consequence","meaning":"(n.) 结果；后果"},
{"word":"conservation","meaning":"(n.) 保存；保护"},
{"word":"conservative","meaning":"(adj.) 保守的 (n.) 保守者"},
{"word":"considerable","meaning":"(adj.) 相当大的；重要的"},
{"word":"considerate","meaning":"(adj.) 体贴的；考虑周到的"},
{"word":"consist","meaning":"(v.) 由…组成；在于"},
{"word":"consistent","meaning":"(adj.) 一致的；始终如一的"},
{"word":"consolidate","meaning":"(v.) 巩固；合并"},
{"word":"conspicuous","meaning":"(adj.) 显眼的；显著的"},
{"word":"constant","meaning":"(adj.) 不断的；恒定的 (n.) 常数"},
{"word":"constitute","meaning":"(v.) 构成；组成"},
{"word":"constitution","meaning":"(n.) 宪法；体质"},
{"word":"construct","meaning":"(v.) 建造；构建"},
{"word":"consult","meaning":"(v.) 咨询；请教"},
{"word":"consume","meaning":"(v.) 消耗；消费"},
{"word":"consumption","meaning":"(n.) 消耗；消费"},
{"word":"contemplate","meaning":"(v.) 沉思；注视"},
{"word":"contemporary","meaning":"(adj.) 当代的 (n.) 同代人"},
{"word":"contempt","meaning":"(n.) 轻视；蔑视"},
{"word":"contend","meaning":"(v.) 竞争；争辩"},
{"word":"content","meaning":"(n.) 内容 (adj.) 满足的"},
{"word":"contest","meaning":"(n.) 比赛；竞赛 (v.) 质疑"},
{"word":"context","meaning":"(n.) 上下文；背景"},
{"word":"continual","meaning":"(adj.) 持续的；频繁的"},
{"word":"contract","meaning":"(n.) 合同 (v.) 收缩；订约"},
{"word":"contradict","meaning":"(v.) 反驳；与…矛盾"},
{"word":"contrary","meaning":"(adj.) 相反的 (n.) 相反"},
{"word":"contrast","meaning":"(v./n.) 对比；差异"},
{"word":"contribute","meaning":"(v.) 贡献；捐助"},
{"word":"controversial","meaning":"(adj.) 有争议的"},
{"word":"controversy","meaning":"(n.) 争论；争议"},
{"word":"convenient","meaning":"(adj.) 方便的；便利的"},
{"word":"convention","meaning":"(n.) 惯例；大会"},
{"word":"conventional","meaning":"(adj.) 传统的；常规的"},
{"word":"convert","meaning":"(v.) 转换；改变信仰"},
{"word":"convey","meaning":"(v.) 传达；运送"},
{"word":"convince","meaning":"(v.) 使确信；说服"},
{"word":"cooperative","meaning":"(adj.) 合作的 (n.) 合作社"},
{"word":"cope","meaning":"(v.) 应付；处理"},
{"word":"corporate","meaning":"(adj.) 公司的；法人的"},
{"word":"correct","meaning":"(adj.) 正确的 (v.) 纠正"},
{"word":"correlate","meaning":"(v.) 相关；关联"},
{"word":"correspond","meaning":"(v.) 符合；通信"},
{"word":"corresponding","meaning":"(adj.) 相应的；对应的"},
{"word":"corrode","meaning":"(v.) 腐蚀；侵蚀"},
{"word":"corrupt","meaning":"(adj.) 腐败的 (v.) 使腐败"},
{"word":"costly","meaning":"(adj.) 昂贵的；代价高的"},
{"word":"counsel","meaning":"(v./n.) 劝告；建议"},
{"word":"counterpart","meaning":"(n.) 对应的人/物"},
{"word":"countless","meaning":"(adj.) 无数的"},
{"word":"courage","meaning":"(n.) 勇气；胆量"},
{"word":"courteous","meaning":"(adj.) 有礼貌的"},
{"word":"crash","meaning":"(v./n.) 碰撞；坠毁"},
{"word":"creative","meaning":"(adj.) 创造性的"},
{"word":"crisis","meaning":"(n.) 危机；紧要关头"},
{"word":"criteria","meaning":"(n.) 标准；准则(复数)"},
{"word":"crucial","meaning":"(adj.) 关键的；决定性的"},
{"word":"cultivate","meaning":"(v.) 培养；耕作"},
{"word":"cumulative","meaning":"(adj.) 累积的"},
{"word":"curiosity","meaning":"(n.) 好奇心"},
{"word":"curious","meaning":"(adj.) 好奇的"},
{"word":"currency","meaning":"(n.) 货币；通用"},
{"word":"curriculum","meaning":"(n.) 课程"},
{"word":"customary","meaning":"(adj.) 习惯的；惯例的"},
{"word":"cynical","meaning":"(adj.) 愤世嫉俗的"},
{"word":"dazzling","meaning":"(adj.) 耀眼的；令人惊叹的"},
{"word":"deadline","meaning":"(n.) 截止日期"},
{"word":"deadly","meaning":"(adj.) 致命的 (adv.) 非常"},
{"word":"debate","meaning":"(v./n.) 辩论；讨论"},
{"word":"decay","meaning":"(v./n.) 衰退；腐烂"},
{"word":"deceive","meaning":"(v.) 欺骗；蒙蔽"},
{"word":"decent","meaning":"(adj.) 正派的；体面的"},
{"word":"decisive","meaning":"(adj.) 决定性的；果断的"},
{"word":"declaration","meaning":"(n.) 宣言；声明"},
{"word":"decline","meaning":"(v.) 下降；拒绝 (n.) 下降"},
{"word":"decompose","meaning":"(v.) 分解；腐烂"},
{"word":"dedicate","meaning":"(v.) 奉献；致力于"},
{"word":"deduce","meaning":"(v.) 推论；演绎"},
{"word":"deem","meaning":"(v.) 认为；视为"},
{"word":"defect","meaning":"(n.) 缺陷；缺点 (v.) 叛变"},
{"word":"deficiency","meaning":"(n.) 缺乏；不足"},
{"word":"deficit","meaning":"(n.) 赤字；逆差"},
{"word":"define","meaning":"(v.) 定义；界定"},
{"word":"definite","meaning":"(adj.) 明确的；肯定的"},
{"word":"defy","meaning":"(v.) 违抗；蔑视"},
{"word":"deliberate","meaning":"(adj.) 故意的 (v.) 深思熟虑"},
{"word":"delicate","meaning":"(adj.) 精致的；微妙的"},
{"word":"deliver","meaning":"(v.) 递送；发表"},
{"word":"demand","meaning":"(v./n.) 要求；需求"},
{"word":"democracy","meaning":"(n.) 民主"},
{"word":"demonstrate","meaning":"(v.) 证明；示范；示威"},
{"word":"denial","meaning":"(n.) 否认；拒绝"},
{"word":"denote","meaning":"(v.) 表示；意味着"},
{"word":"dense","meaning":"(adj.) 密集的；浓厚的"},
{"word":"departure","meaning":"(n.) 离开；出发"},
{"word":"depict","meaning":"(v.) 描绘；描述"},
{"word":"deplete","meaning":"(v.) 耗尽；使枯竭"},
{"word":"deploy","meaning":"(v.) 部署；展开"},
{"word":"deposit","meaning":"(v.) 存放；沉积 (n.) 存款；押金"},
{"word":"depress","meaning":"(v.) 使沮丧；压下"},
{"word":"deprive","meaning":"(v.) 剥夺；使丧失"},
{"word":"derive","meaning":"(v.) 获得；源于"},
{"word":"descend","meaning":"(v.) 下降；下来"},
{"word":"deserve","meaning":"(v.) 值得；应受"},
{"word":"designate","meaning":"(v.) 指定；指派"},
{"word":"desirable","meaning":"(adj.) 令人向往的；可取的"},
{"word":"desperate","meaning":"(adj.) 绝望的；不顾一切的"},
{"word":"despise","meaning":"(v.) 鄙视；蔑视"},
{"word":"destination","meaning":"(n.) 目的地"},
{"word":"destined","meaning":"(adj.) 注定的；命定的"},
{"word":"destruction","meaning":"(n.) 破坏；毁灭"},
{"word":"destructive","meaning":"(adj.) 破坏性的"},
{"word":"detach","meaning":"(v.) 分离；拆下"},
{"word":"detect","meaning":"(v.) 发现；察觉"},
{"word":"deteriorate","meaning":"(v.) 恶化；变坏"},
{"word":"determine","meaning":"(v.) 决定；确定"},
{"word":"devastate","meaning":"(v.) 毁灭；破坏"},
{"word":"devise","meaning":"(v.) 设计；发明"},
{"word":"devote","meaning":"(v.) 奉献；致力于"},
{"word":"diagnose","meaning":"(v.) 诊断"},
{"word":"dictate","meaning":"(v.) 口述；命令 (n.) 命令"},
{"word":"dilemma","meaning":"(n.) 困境；两难"},
{"word":"dimension","meaning":"(n.) 尺寸；维度"},
{"word":"diminish","meaning":"(v.) 减少；缩小"},
{"word":"diplomatic","meaning":"(adj.) 外交的；有策略的"},
{"word":"direction","meaning":"(n.) 方向；指导"},
{"word":"disability","meaning":"(n.) 残疾；无能"},
{"word":"disadvantage","meaning":"(n.) 不利；劣势"},
{"word":"disappear","meaning":"(v.) 消失；不见"},
{"word":"disappoint","meaning":"(v.) 使失望"},
{"word":"disaster","meaning":"(n.) 灾难"},
{"word":"discard","meaning":"(v.) 丢弃；抛弃"},
{"word":"discern","meaning":"(v.) 辨别；识别"},
{"word":"discharge","meaning":"(v.) 释放；排出 (n.) 释放"},
{"word":"discipline","meaning":"(n.) 纪律；学科 (v.) 训练"},
{"word":"disclose","meaning":"(v.) 揭露；公开"},
{"word":"discount","meaning":"(n.) 折扣 (v.) 打折"},
{"word":"discourage","meaning":"(v.) 使泄气；阻止"},
{"word":"discrete","meaning":"(adj.) 离散的；不相关的"},
{"word":"discrimination","meaning":"(n.) 歧视；辨别力"},
{"word":"disgrace","meaning":"(n.) 耻辱 (v.) 使丢脸"},
{"word":"disguise","meaning":"(v./n.) 伪装；假扮"},
{"word":"disintegrate","meaning":"(v.) 崩溃；瓦解"},
{"word":"dismiss","meaning":"(v.) 解雇；驳回"},
{"word":"disorder","meaning":"(n.) 混乱；失调"},
{"word":"dispatch","meaning":"(v.) 派遣；发送 (n.) 急件"},
{"word":"disperse","meaning":"(v.) 分散；驱散"},
{"word":"displace","meaning":"(v.) 取代；转移"},
{"word":"display","meaning":"(v./n.) 展示；陈列"},
{"word":"disposal","meaning":"(n.) 处理；支配"},
{"word":"dispose","meaning":"(v.) 处理；安排"},
{"word":"dispute","meaning":"(v./n.) 争论；纠纷"},
{"word":"disrupt","meaning":"(v.) 扰乱；破坏"},
{"word":"dissolve","meaning":"(v.) 溶解；解散"},
{"word":"distinct","meaning":"(adj.) 明显的；独特的"},
{"word":"distinction","meaning":"(n.) 区别；荣誉"},
{"word":"distinguish","meaning":"(v.) 区分；辨别"},
{"word":"distort","meaning":"(v.) 扭曲；曲解"},
{"word":"distract","meaning":"(v.) 分散注意力；使分心"},
{"word":"distress","meaning":"(n.) 痛苦；危难 (v.) 使痛苦"},
{"word":"distribute","meaning":"(v.) 分配；分布"},
{"word":"disturb","meaning":"(v.) 打扰；扰乱"},
{"word":"diverse","meaning":"(adj.) 多样的；不同的"},
{"word":"diversity","meaning":"(n.) 多样性；差异"},
{"word":"divert","meaning":"(v.) 转移；使转向"},
{"word":"divine","meaning":"(adj.) 神圣的；神的"},
{"word":"doctrine","meaning":"(n.) 教义；学说"},
{"word":"document","meaning":"(n.) 文件 (v.) 记录"},
{"word":"domain","meaning":"(n.) 领域；范围"},
{"word":"domestic","meaning":"(adj.) 国内的；家庭的"},
{"word":"dominant","meaning":"(adj.) 支配的；主要的"},
{"word":"dominate","meaning":"(v.) 支配；控制"},
{"word":"donate","meaning":"(v.) 捐赠"},
{"word":"doom","meaning":"(n.) 厄运 (v.) 注定"},
{"word":"dose","meaning":"(n.) 剂量；一剂"},
{"word":"doubtful","meaning":"(adj.) 怀疑的；不确定的"},
{"word":"drain","meaning":"(v.) 排水；耗尽 (n.) 排水沟"},
{"word":"dramatic","meaning":"(adj.) 戏剧性的；引人注目的"},
{"word":"drastic","meaning":"(adj.) 激烈的；极端的"},
{"word":"drawback","meaning":"(n.) 缺点；障碍"},
{"word":"drift","meaning":"(v.) 漂流 (n.) 漂流；趋势"},
{"word":"drought","meaning":"(n.) 干旱"},
{"word":"dubious","meaning":"(adj.) 怀疑的；不可靠的"},
{"word":"duplicate","meaning":"(v.) 复制 (adj.) 副本的 (n.) 副本"},
{"word":"durable","meaning":"(adj.) 耐用的；持久的"},
{"word":"dwelling","meaning":"(n.) 住所；住宅"},
{"word":"dynamic","meaning":"(adj.) 动态的；充满活力的"},
{"word":"earnest","meaning":"(adj.) 认真的；诚挚的"},
{"word":"eccentric","meaning":"(adj.) 古怪的 (n.) 怪人"},
{"word":"echo","meaning":"(v./n.) 回声；共鸣"},
{"word":"ecological","meaning":"(adj.) 生态的；生态学的"},
{"word":"economy","meaning":"(n.) 经济；节约"},
{"word":"edge","meaning":"(n.) 边缘；优势 (v.) 缓慢移动"},
{"word":"edible","meaning":"(adj.) 可食用的"},
{"word":"effective","meaning":"(adj.) 有效的；实际的"},
{"word":"efficient","meaning":"(adj.) 高效的；有效率的"},
{"word":"elaborate","meaning":"(adj.) 精心制作的 (v.) 详细阐述"},
{"word":"elbow","meaning":"(n.) 肘 (v.) 用肘推"},
{"word":"elegant","meaning":"(adj.) 优雅的；精美的"},
{"word":"element","meaning":"(n.) 元素；要素"},
{"word":"elevate","meaning":"(v.) 提升；举起"},
{"word":"eligible","meaning":"(adj.) 有资格的；合适的"},
{"word":"eliminate","meaning":"(v.) 消除；淘汰"},
{"word":"elite","meaning":"(n.) 精英 (adj.) 精英的"},
{"word":"eloquent","meaning":"(adj.) 雄辩的；有说服力的"},
{"word":"embark","meaning":"(v.) 着手；上船"},
{"word":"embarrass","meaning":"(v.) 使尴尬；使窘迫"},
{"word":"embed","meaning":"(v.) 嵌入；使嵌入"},
{"word":"embody","meaning":"(v.) 体现；包含"},
{"word":"embrace","meaning":"(v.) 拥抱；接受 (n.) 拥抱"},
{"word":"emerge","meaning":"(v.) 出现；浮现"},
{"word":"emigrate","meaning":"(v.) 移居国外"},
{"word":"emission","meaning":"(n.) 排放；散发"},
{"word":"emotion","meaning":"(n.) 情感；情绪"},
{"word":"emphasize","meaning":"(v.) 强调；着重"},
{"word":"empirical","meaning":"(adj.) 经验的；实证的"},
{"word":"employ","meaning":"(v.) 雇用；使用"},
{"word":"encounter","meaning":"(v./n.) 遭遇；邂逅"},
{"word":"encourage","meaning":"(v.) 鼓励；促进"},
{"word":"endanger","meaning":"(v.) 危及；危害"},
{"word":"endeavor","meaning":"(v./n.) 努力；尝试"},
{"word":"endow","meaning":"(v.) 赋予；捐赠"},
{"word":"endure","meaning":"(v.) 忍受；持续"},
{"word":"enforce","meaning":"(v.) 执行；强制"},
{"word":"engage","meaning":"(v.) 从事；吸引；订婚"},
{"word":"enhance","meaning":"(v.) 增强；提高"},
{"word":"enlighten","meaning":"(v.) 启发；开导"},
{"word":"enormous","meaning":"(adj.) 巨大的"},
{"word":"enrich","meaning":"(v.) 使丰富；使充实"},
{"word":"ensure","meaning":"(v.) 确保；保证"},
{"word":"enterprise","meaning":"(n.) 企业；事业"},
{"word":"enthusiasm","meaning":"(n.) 热情；热忱"},
{"word":"entitle","meaning":"(v.) 使有权；给…命名"},
{"word":"entity","meaning":"(n.) 实体；存在"},
{"word":"envision","meaning":"(v.) 想象；展望"},
{"word":"epidemic","meaning":"(n.) 流行病 (adj.) 流行的"},
{"word":"episode","meaning":"(n.) 一集；事件"},
{"word":"equal","meaning":"(adj.) 相等的 (v.) 等于"},
{"word":"equip","meaning":"(v.) 装备；配备"},
{"word":"equivalent","meaning":"(adj.) 等价的 (n.) 等价物"},
{"word":"erect","meaning":"(v.) 建造；竖立 (adj.) 直立的"},
{"word":"erosion","meaning":"(n.) 侵蚀；腐蚀"},
{"word":"erroneous","meaning":"(adj.) 错误的；不正确的"},
{"word":"erupt","meaning":"(v.) 爆发；喷发"},
{"word":"escalate","meaning":"(v.) 升级；加剧"},
{"word":"escape","meaning":"(v./n.) 逃跑；逃避"},
{"word":"essential","meaning":"(adj.) 本质的；必要的 (n.) 要素"},
{"word":"establish","meaning":"(v.) 建立；确立"},
{"word":"estate","meaning":"(n.) 地产；财产"},
{"word":"estimate","meaning":"(v.) 估计 (n.) 估计；估价"},
{"word":"evaluate","meaning":"(v.) 评估；评价"},
{"word":"evaporate","meaning":"(v.) 蒸发；消失"},
{"word":"evidence","meaning":"(n.) 证据；迹象"},
{"word":"evident","meaning":"(adj.) 明显的；明白的"},
{"word":"evoke","meaning":"(v.) 唤起；引起"},
{"word":"evolution","meaning":"(n.) 进化；演变"},
{"word":"exaggerate","meaning":"(v.) 夸大；夸张"},
{"word":"examine","meaning":"(v.) 检查；审查"},
{"word":"exceed","meaning":"(v.) 超过；超出"},
{"word":"exception","meaning":"(n.) 例外；异议"},
{"word":"exceptional","meaning":"(adj.) 杰出的；异常的"},
{"word":"excessive","meaning":"(adj.) 过度的；过多的"},
{"word":"exclude","meaning":"(v.) 排除；排斥"},
{"word":"exclusive","meaning":"(adj.) 独占的；排外的"},
{"word":"execute","meaning":"(v.) 执行；处决"},
{"word":"exemplify","meaning":"(v.) 例证；作为…的榜样"},
{"word":"exempt","meaning":"(v.) 免除 (adj.) 被免除的"},
{"word":"exert","meaning":"(v.) 施加；发挥"},
{"word":"exhaust","meaning":"(v.) 耗尽；使筋疲力尽 (n.) 废气"},
{"word":"exhibit","meaning":"(v.) 展示 (n.) 展品"},
{"word":"exist","meaning":"(v.) 存在；生存"},
{"word":"expand","meaning":"(v.) 扩大；膨胀"},
{"word":"expedition","meaning":"(n.) 远征；探险"},
{"word":"expel","meaning":"(v.) 驱逐；开除"},
{"word":"expend","meaning":"(v.) 花费；消耗"},
{"word":"expense","meaning":"(n.) 费用；开支"},
{"word":"expertise","meaning":"(n.) 专业知识；专长"},
{"word":"expire","meaning":"(v.) 期满；终止"},
{"word":"explicit","meaning":"(adj.) 明确的；清楚的"},
{"word":"exploit","meaning":"(v.) 利用；剥削 (n.) 功绩"},
{"word":"explore","meaning":"(v.) 探索；探究"},
{"word":"expose","meaning":"(v.) 暴露；揭露"},
{"word":"exposure","meaning":"(n.) 暴露；接触"},
{"word":"extend","meaning":"(v.) 延伸；扩展"},
{"word":"extensive","meaning":"(adj.) 广泛的；大量的"},
{"word":"extent","meaning":"(n.) 程度；范围"},
{"word":"exterior","meaning":"(adj.) 外部的 (n.) 外部"},
{"word":"external","meaning":"(adj.) 外部的；外面的"},
{"word":"extinct","meaning":"(adj.) 灭绝的；消亡的"},
{"word":"extinguish","meaning":"(v.) 熄灭；消灭"},
{"word":"extract","meaning":"(v.) 提取；摘录 (n.) 提取物"},
{"word":"extraordinary","meaning":"(adj.) 非凡的；特别的"},
{"word":"extravagant","meaning":"(adj.) 奢侈的；过度的"},
{"word":"extreme","meaning":"(adj.) 极端的 (n.) 极端"},
{"word":"fabricate","meaning":"(v.) 编造；制造"},
{"word":"facilitate","meaning":"(v.) 促进；使便利"},
{"word":"facilities","meaning":"(n.) 设施；设备"},
{"word":"fascinates","meaning":"(v.) 使着迷；吸引"},
{"word":"fatigue","meaning":"(n.) 疲劳；劳累"},
{"word":"fault","meaning":"(n.) 错误；缺点"},
{"word":"feat","meaning":"(n.) 功绩；伟业"},
{"word":"feature","meaning":"(n.) 特征；特色 (v.) 以…为特色"},
{"word":"federal","meaning":"(adj.) 联邦的"},
{"word":"fellow","meaning":"(n.) 家伙；同伴 (adj.) 同伴的"},
{"word":"feminine","meaning":"(adj.) 女性的；阴柔的"},
{"word":"fierce","meaning":"(adj.) 凶猛的；激烈的"},
{"word":"finance","meaning":"(n.) 财政；金融 (v.) 资助"},
{"word":"finite","meaning":"(adj.) 有限的"},
{"word":"flaw","meaning":"(n.) 缺陷；瑕疵"},
{"word":"flexible","meaning":"(adj.) 灵活的；可变通的"},
{"word":"flourish","meaning":"(v.) 繁荣；茂盛"},
{"word":"fluctuate","meaning":"(v.) 波动；起伏"},
{"word":"focus","meaning":"(v.) 集中 (n.) 焦点"},
{"word":"forbid","meaning":"(v.) 禁止；不许"},
{"word":"forecast","meaning":"(v./n.) 预测；预报"},
{"word":"foremost","meaning":"(adj.) 最重要的 (adv.) 首先"},
{"word":"forge","meaning":"(v.) 锻造；伪造 (n.) 铁匠铺"},
{"word":"formal","meaning":"(adj.) 正式的；形式的"},
{"word":"format","meaning":"(n.) 格式 (v.) 格式化"},
{"word":"formidable","meaning":"(adj.) 可怕的；强大的"},
{"word":"formula","meaning":"(n.) 公式；配方"},
{"word":"formulate","meaning":"(v.) 制定；构想"},
{"word":"forthcoming","meaning":"(adj.) 即将到来的"},
{"word":"fortune","meaning":"(n.) 财富；运气"},
{"word":"foster","meaning":"(v.) 培养；促进"},
{"word":"fraction","meaning":"(n.) 分数；小部分"},
{"word":"fragment","meaning":"(n.) 碎片；片段 (v.) 分裂"},
{"word":"frame","meaning":"(n.) 框架；帧 (v.) 设计；陷害"},
{"word":"franchise","meaning":"(n.) 特许经营权；选举权"},
{"word":"frantic","meaning":"(adj.) 疯狂的；狂乱的"},
{"word":"fraud","meaning":"(n.) 欺诈；骗子"},
{"word":"frequent","meaning":"(adj.) 频繁的"},
{"word":"friction","meaning":"(n.) 摩擦；冲突"},
{"word":"frontier","meaning":"(n.) 边境；前沿"},
{"word":"frustrate","meaning":"(v.) 使沮丧；挫败"},
{"word":"fulfill","meaning":"(v.) 实现；履行"},
{"word":"function","meaning":"(n.) 功能；函数 (v.) 运行"},
{"word":"fundamental","meaning":"(adj.) 基本的；根本的"},
{"word":"furious","meaning":"(adj.) 狂怒的；激烈的"},
{"word":"furnish","meaning":"(v.) 装修；提供"},
{"word":"futile","meaning":"(adj.) 徒劳的；无用的"},
{"word":"gain","meaning":"(v.) 获得；增加 (n.) 收益"},
{"word":"galaxy","meaning":"(n.) 星系；银河"},
{"word":"gap","meaning":"(n.) 差距；缺口"},
{"word":"garment","meaning":"(n.) 衣服；服装"},
{"word":"gather","meaning":"(v.) 聚集；收集"},
{"word":"gaze","meaning":"(v./n.) 凝视；注视"},
{"word":"generate","meaning":"(v.) 产生；发生"},
{"word":"generous","meaning":"(adj.) 慷慨的；大量的"},
{"word":"genetic","meaning":"(adj.) 遗传的；基因的"},
{"word":"genuine","meaning":"(adj.) 真正的；真诚的"},
{"word":"gesture","meaning":"(n.) 手势；姿态 (v.) 做手势"},
{"word":"gigantic","meaning":"(adj.) 巨大的"},
{"word":"glamour","meaning":"(n.) 魅力；吸引力"},
{"word":"glimpse","meaning":"(n.) 一瞥 (v.) 瞥见"},
{"word":"global","meaning":"(adj.) 全球的；全面的"},
{"word":"gloomy","meaning":"(adj.) 阴暗的；悲观的"},
{"word":"glorious","meaning":"(adj.) 光荣的；辉煌的"},
{"word":"govern","meaning":"(v.) 统治；管理"},
{"word":"grace","meaning":"(n.) 优雅；恩典"},
{"word":"gradual","meaning":"(adj.) 逐渐的；逐步的"},
{"word":"grant","meaning":"(v.) 授予；同意 (n.) 拨款"},
{"word":"graphic","meaning":"(adj.) 图形的；生动的"},
{"word":"grasp","meaning":"(v.) 抓住；理解 (n.) 抓握"},
{"word":"grateful","meaning":"(adj.) 感激的"},
{"word":"grave","meaning":"(adj.) 严重的 (n.) 坟墓"},
{"word":"gravity","meaning":"(n.) 重力；严重性"},
{"word":"grieve","meaning":"(v.) 悲伤；哀悼"},
{"word":"grim","meaning":"(adj.) 严酷的；可怕的"},
{"word":"grip","meaning":"(v.) 紧握；吸引 (n.) 紧握"},
{"word":"gross","meaning":"(adj.) 总的；粗俗的"},
{"word":"guarantee","meaning":"(v./n.) 保证；担保"},
{"word":"guidance","meaning":"(n.) 指导；引导"},
{"word":"guilty","meaning":"(adj.) 有罪的；内疚的"},
{"word":"habitat","meaning":"(n.) 栖息地"},
{"word":"halt","meaning":"(v./n.) 停止；暂停"},
{"word":"hamper","meaning":"(v.) 妨碍；阻碍"},
{"word":"handful","meaning":"(n.) 一把；少数"},
{"word":"handle","meaning":"(v.) 处理 (n.) 把手"},
{"word":"harbor","meaning":"(n.) 港口 (v.) 庇护；怀有"},
{"word":"hardship","meaning":"(n.) 困难；苦难"},
{"word":"harmony","meaning":"(n.) 和谐；协调"},
{"word":"harsh","meaning":"(adj.) 严厉的；刺耳的"},
{"word":"haste","meaning":"(n.) 急忙；仓促"},
{"word":"hazard","meaning":"(n.) 危险 (v.) 冒险"},
{"word":"headquarters","meaning":"(n.) 总部；司令部"},
{"word":"heal","meaning":"(v.) 治愈；愈合"},
{"word":"heritage","meaning":"(n.) 遗产；传统"},
{"word":"hesitate","meaning":"(v.) 犹豫；踌躇"},
{"word":"highlight","meaning":"(v.) 强调；突出 (n.) 亮点"},
{"word":"hinder","meaning":"(v.) 阻碍；妨碍"},
{"word":"hint","meaning":"(n.) 暗示；提示 (v.) 暗示"},
{"word":"horizon","meaning":"(n.) 地平线；视野"},
{"word":"horrible","meaning":"(adj.) 可怕的；极差的"},
{"word":"hostile","meaning":"(adj.) 敌对的；不友好的"},
{"word":"humble","meaning":"(adj.) 谦虚的；卑微的 (v.) 贬低"},
{"word":"hypothesis","meaning":"(n.) 假设；假说"},
{"word":"identical","meaning":"(adj.) 相同的；一样的"},
{"word":"identify","meaning":"(v.) 识别；确认"},
{"word":"ideology","meaning":"(n.) 意识形态；思想体系"},
{"word":"ignorance","meaning":"(n.) 无知；愚昧"},
{"word":"ignore","meaning":"(v.) 忽视；不理"},
{"word":"illuminate","meaning":"(v.) 照亮；阐明"},
{"word":"illusion","meaning":"(n.) 幻觉；错觉"},
{"word":"illustrate","meaning":"(v.) 说明；图解"},
{"word":"immense","meaning":"(adj.) 巨大的；广大的"},
{"word":"immigrant","meaning":"(n.) 移民"},
{"word":"immune","meaning":"(adj.) 免疫的；不受影响的"},
{"word":"impact","meaning":"(n.) 影响；冲击 (v.) 影响"},
{"word":"impair","meaning":"(v.) 损害；削弱"},
{"word":"impartial","meaning":"(adj.) 公正的；中立的"},
{"word":"imperative","meaning":"(adj.) 必要的；命令的 (n.) 必要的事"},
{"word":"implement","meaning":"(v.) 实施 (n.) 工具"},
{"word":"implication","meaning":"(n.) 含义；暗示"},
{"word":"implicit","meaning":"(adj.) 含蓄的；隐含的"},
{"word":"impose","meaning":"(v.) 强加；征收"},
{"word":"impressive","meaning":"(adj.) 令人印象深刻的"},
{"word":"impulse","meaning":"(n.) 冲动；脉冲"},
{"word":"inadequate","meaning":"(adj.) 不充分的；不适当的"},
{"word":"inaugurate","meaning":"(v.) 开创；使就职"},
{"word":"incentive","meaning":"(n.) 激励；动机"},
{"word":"incidence","meaning":"(n.) 发生率； incidence"},
{"word":"inclined","meaning":"(adj.) 倾向的；有…意向的"},
{"word":"inclusive","meaning":"(adj.) 包容的；包括的"},
{"word":"incorporate","meaning":"(v.) 包含；合并"},
{"word":"incredible","meaning":"(adj.) 难以置信的"},
{"word":"incur","meaning":"(v.) 招致；引起"},
{"word":"indefinite","meaning":"(adj.) 不确定的；无限期的"},
{"word":"indicate","meaning":"(v.) 表明；指示"},
{"word":"indifferent","meaning":"(adj.) 冷漠的；不关心的"},
{"word":"indigenous","meaning":"(adj.) 本土的；土生土长的"},
{"word":"indispensable","meaning":"(adj.) 不可缺少的"},
{"word":"individual","meaning":"(adj.) 个别的 (n.) 个人"},
{"word":"induce","meaning":"(v.) 引起；诱导"},
{"word":"indulge","meaning":"(v.) 沉溺；放纵"},
{"word":"industrial","meaning":"(adj.) 工业的；产业的"},
{"word":"inevitable","meaning":"(adj.) 不可避免的"},
{"word":"infant","meaning":"(n.) 婴儿 (adj.) 婴儿的"},
{"word":"infect","meaning":"(v.) 感染；传染"},
{"word":"inferior","meaning":"(adj.) 低等的；差的 (n.) 下属"},
{"word":"infinite","meaning":"(adj.) 无限的；无穷的"},
{"word":"inflation","meaning":"(n.) 通货膨胀"},
{"word":"influence","meaning":"(v./n.) 影响；势力"},
{"word":"infrastructure","meaning":"(n.) 基础设施"},
{"word":"ingenious","meaning":"(adj.) 巧妙的；有创造力的"},
{"word":"inhabit","meaning":"(v.) 居住；栖息"},
{"word":"inherent","meaning":"(adj.) 固有的；内在的"},
{"word":"inherit","meaning":"(v.) 继承"},
{"word":"inhibit","meaning":"(v.) 抑制；阻止"},
{"word":"initial","meaning":"(adj.) 最初的 (n.) 首字母"},
{"word":"initiate","meaning":"(v.) 发起；开始"},
{"word":"inject","meaning":"(v.) 注射；注入"},
{"word":"innate","meaning":"(adj.) 天生的；固有的"},
{"word":"innovation","meaning":"(n.) 创新；革新"},
{"word":"innumerable","meaning":"(adj.) 无数的"},
{"word":"inquire","meaning":"(v.) 询问；调查"},
{"word":"insert","meaning":"(v.) 插入 (n.) 插页"},
{"word":"insight","meaning":"(n.) 洞察力；见解"},
{"word":"inspect","meaning":"(v.) 检查；视察"},
{"word":"inspiration","meaning":"(n.) 灵感；鼓舞"},
{"word":"install","meaning":"(v.) 安装；设置"},
{"word":"instance","meaning":"(n.) 例子；实例"},
{"word":"instant","meaning":"(adj.) 立即的 (n.) 瞬间"},
{"word":"instinct","meaning":"(n.) 本能；直觉"},
{"word":"institute","meaning":"(n.) 学院；研究所 (v.) 制定"},
{"word":"institution","meaning":"(n.) 机构；制度"},
{"word":"instruct","meaning":"(v.) 指导；指示"},
{"word":"instrument","meaning":"(n.) 仪器；乐器"},
{"word":"insulate","meaning":"(v.) 隔离；使绝缘"},
{"word":"insult","meaning":"(v./n.) 侮辱；冒犯"},
{"word":"insurance","meaning":"(n.) 保险"},
{"word":"intact","meaning":"(adj.) 完好无损的"},
{"word":"integral","meaning":"(adj.) 必需的；完整的"},
{"word":"integrate","meaning":"(v.) 整合；融入"},
{"word":"integrity","meaning":"(n.) 正直；完整"},
{"word":"intellectual","meaning":"(adj.) 智力的 (n.) 知识分子"},
{"word":"intelligent","meaning":"(adj.) 聪明的；智能的"},
{"word":"intense","meaning":"(adj.) 强烈的；紧张的"},
{"word":"intensify","meaning":"(v.) 加强；加剧"},
{"word":"intensive","meaning":"(adj.) 密集的；集约的"},
{"word":"intention","meaning":"(n.) 意图；目的"},
{"word":"interact","meaning":"(v.) 互动；相互作用"},
{"word":"interfere","meaning":"(v.) 干涉；妨碍"},
{"word":"interior","meaning":"(adj.) 内部的 (n.) 内部"},
{"word":"intermediate","meaning":"(adj.) 中间的；中级的"},
{"word":"internal","meaning":"(adj.) 内部的；国内的"},
{"word":"interpret","meaning":"(v.) 解释；口译"},
{"word":"intervene","meaning":"(v.) 干预；介入"},
{"word":"intimate","meaning":"(adj.) 亲密的 (v.) 暗示"},
{"word":"intricate","meaning":"(adj.) 复杂的；精细的"},
{"word":"intrinsic","meaning":"(adj.) 内在的；本质的"},
{"word":"intuition","meaning":"(n.) 直觉"},
{"word":"invade","meaning":"(v.) 侵入；侵略"},
{"word":"invalid","meaning":"(adj.) 无效的；病弱的"},
{"word":"invaluable","meaning":"(adj.) 极宝贵的"},
{"word":"invariable","meaning":"(adj.) 不变的；恒定的"},
{"word":"invasion","meaning":"(n.) 入侵；侵略"},
{"word":"investigate","meaning":"(v.) 调查；研究"},
{"word":"involve","meaning":"(v.) 涉及；包含"},
{"word":"ironic","meaning":"(adj.) 讽刺的"},
{"word":"irrelevant","meaning":"(adj.) 不相关的"},
{"word":"irreplaceable","meaning":"(adj.) 不可替代的"},
{"word":"irresistible","meaning":"(adj.) 无法抗拒的"},
{"word":"isolate","meaning":"(v.) 隔离；孤立"},
{"word":"issue","meaning":"(n.) 问题；发行 (v.) 发行；发布"},
{"word":"jeopardize","meaning":"(v.) 危害；损害"},
{"word":"journal","meaning":"(n.) 期刊；日志"},
{"word":"justify","meaning":"(v.) 证明…正当；为…辩护"},
{"word":"juvenile","meaning":"(adj.) 青少年的 (n.) 青少年"},
{"word":"keen","meaning":"(adj.) 渴望的；敏锐的"},
{"word":"label","meaning":"(n.) 标签 (v.) 标注"},
{"word":"landscape","meaning":"(n.) 风景；格局"},
{"word":"lapse","meaning":"(n.) 失误；流逝 (v.) 失效"},
{"word":"launch","meaning":"(v.) 发射；发起 (n.) 发射"},
{"word":"legitimate","meaning":"(adj.) 合法的；正当的"},
{"word":"leisure","meaning":"(n.) 闲暇；休闲"},
{"word":"liberal","meaning":"(adj.) 自由的；慷慨的"},
{"word":"liberty","meaning":"(n.) 自由；释放"},
{"word":"likewise","meaning":"(adv.) 同样地；也"},
{"word":"limitation","meaning":"(n.) 限制；局限性"},
{"word":"linger","meaning":"(v.) 逗留；徘徊"},
{"word":"literacy","meaning":"(n.) 读写能力"},
{"word":"literal","meaning":"(adj.) 字面的；逐字的"},
{"word":"litter","meaning":"(n.) 垃圾 (v.) 乱扔"},
{"word":"livestock","meaning":"(n.) 家畜；牲畜"},
{"word":"locomotive","meaning":"(n.) 火车头 (adj.) 运动的"},
{"word":"logical","meaning":"(adj.) 逻辑的；合理的"},
{"word":"loyal","meaning":"(adj.) 忠诚的"},
{"word":"luxury","meaning":"(n.) 奢侈；奢华"},
{"word":"magically","meaning":"(adv.) 魔术般地；不可思议地"},
{"word":"magnified","meaning":"(v.) 放大；夸大"},
{"word":"majestic","meaning":"(adj.) 雄伟的；壮丽的"},
{"word":"major","meaning":"(adj.) 主要的；重大的"},
{"word":"malignant","meaning":"(adj.) 恶性的；有害的"},
{"word":"mammal","meaning":"(n.) 哺乳动物"},
{"word":"mandatory","meaning":"(adj.) 强制的；法定的"},
{"word":"manifest","meaning":"(adj.) 明显的 (v.) 显示；表明"},
{"word":"manipulate","meaning":"(v.) 操纵；控制"},
{"word":"manual","meaning":"(adj.) 手工的 (n.) 手册"},
{"word":"manufacture","meaning":"(v.) 制造 (n.) 制造业"},
{"word":"margin","meaning":"(n.) 边缘；利润；余地"},
{"word":"massive","meaning":"(adj.) 巨大的；大规模的"},
{"word":"mature","meaning":"(adj.) 成熟的 (v.) 成熟"},
{"word":"maximize","meaning":"(v.) 最大化；使最大"},
{"word":"mechanism","meaning":"(n.) 机制；机械装置"},
{"word":"mediate","meaning":"(v.) 调解；斡旋"},
{"word":"meditate","meaning":"(v.) 冥想；沉思"},
{"word":"melancholy","meaning":"(n.) 忧郁 (adj.) 忧郁的"},
{"word":"memorial","meaning":"(adj.) 纪念的 (n.) 纪念碑"},
{"word":"menace","meaning":"(n.) 威胁 (v.) 威胁"},
{"word":"mental","meaning":"(adj.) 心理的；精神的"},
{"word":"merge","meaning":"(v.) 合并；融合"},
{"word":"merit","meaning":"(n.) 优点；价值 (v.) 值得"},
{"word":"metabolic","meaning":"(adj.) 新陈代谢的"},
{"word":"method","meaning":"(n.) 方法；办法"},
{"word":"metropolitan","meaning":"(adj.) 大都市的"},
{"word":"migrate","meaning":"(v.) 迁移；移居"},
{"word":"militant","meaning":"(adj.) 好战的 (n.) 激进分子"},
{"word":"mingle","meaning":"(v.) 混合；交往"},
{"word":"minimal","meaning":"(adj.) 最小的；最低限度的"},
{"word":"minimize","meaning":"(v.) 最小化；使最小"},
{"word":"minimum","meaning":"(n.) 最低限度 (adj.) 最低的"},
{"word":"minister","meaning":"(n.) 部长；牧师"},
{"word":"minor","meaning":"(adj.) 次要的；较小的"},
{"word":"miracle","meaning":"(n.) 奇迹"},
{"word":"misconception","meaning":"(n.) 误解；错误观念"},
{"word":"misery","meaning":"(n.) 痛苦；悲惨"},
{"word":"misfortune","meaning":"(n.) 不幸；厄运"},
{"word":"mission","meaning":"(n.) 使命；任务"},
{"word":"moderate","meaning":"(adj.) 适度的 (v.) 缓和"},
{"word":"modify","meaning":"(v.) 修改；调整"},
{"word":"monitor","meaning":"(v.) 监控 (n.) 显示器"},
{"word":"monopoly","meaning":"(n.) 垄断；专卖"},
{"word":"morality","meaning":"(n.) 道德；品行"},
{"word":"moreover","meaning":"(adv.) 此外；而且"},
{"word":"mortgage","meaning":"(n.) 抵押贷款 (v.) 抵押"},
{"word":"motion","meaning":"(n.) 运动；动议 (v.) 示意"},
{"word":"motivate","meaning":"(v.) 激励；激发"},
{"word":"motive","meaning":"(n.) 动机；目的"},
{"word":"multitude","meaning":"(n.) 众多；群众"},
{"word":"municipal","meaning":"(adj.) 市政的；地方的"},
{"word":"mutual","meaning":"(adj.) 相互的；共同的"},
{"word":"mysterious","meaning":"(adj.) 神秘的"},
{"word":"narrative","meaning":"(n.) 叙述 (adj.) 叙述的"},
{"word":"nasty","meaning":"(adj.) 令人不快的；恶意的"},
{"word":"navigate","meaning":"(v.) 航行；导航"},
{"word":"necessity","meaning":"(n.) 必要性；必需品"},
{"word":"negative","meaning":"(adj.) 消极的；负的 (n.) 否定"},
{"word":"neglect","meaning":"(v.) 忽视；疏忽 (n.) 忽视"},
{"word":"negotiate","meaning":"(v.) 谈判；协商"},
{"word":"neutral","meaning":"(adj.) 中立的；中性的"},
{"word":"nominal","meaning":"(adj.) 名义上的；微不足道的"},
{"word":"nominate","meaning":"(v.) 提名；任命"},
{"word":"notable","meaning":"(adj.) 显著的；著名的"},
{"word":"notify","meaning":"(v.) 通知；告知"},
{"word":"notion","meaning":"(n.) 概念；想法"},
{"word":"notorious","meaning":"(adj.) 臭名昭著的"},
{"word":"nourish","meaning":"(v.) 滋养；培养"},
{"word":"novel","meaning":"(adj.) 新颖的 (n.) 小说"},
{"word":"nucleus","meaning":"(n.) 核心；原子核"},
{"word":"numerous","meaning":"(adj.) 许多的；大量的"},
{"word":"nurture","meaning":"(v.) 培养；养育 (n.) 养育"},
{"word":"nutrition","meaning":"(n.) 营养"},
{"word":"obedient","meaning":"(adj.) 顺从的；服从的"},
{"word":"objective","meaning":"(adj.) 客观的 (n.) 目标"},
{"word":"oblige","meaning":"(v.) 迫使；施恩于"},
{"word":"obscure","meaning":"(adj.) 模糊的；不知名的 (v.) 掩盖"},
{"word":"observe","meaning":"(v.) 观察；遵守"},
{"word":"obsolete","meaning":"(adj.) 过时的；废弃的"},
{"word":"obstacle","meaning":"(n.) 障碍；阻碍"},
{"word":"obtain","meaning":"(v.) 获得；得到"},
{"word":"obvious","meaning":"(adj.) 明显的；显而易见的"},
{"word":"occasion","meaning":"(n.) 场合；时机"},
{"word":"occupy","meaning":"(v.) 占据；使忙碌"},
{"word":"offend","meaning":"(v.) 冒犯；得罪"},
{"word":"offspring","meaning":"(n.) 后代；子女"},
{"word":"ongoing","meaning":"(adj.) 进行中的"},
{"word":"opponent","meaning":"(n.) 对手；反对者"},
{"word":"oppose","meaning":"(v.) 反对；对抗"},
{"word":"oppress","meaning":"(v.) 压迫；压抑"},
{"word":"optimism","meaning":"(n.) 乐观；乐观主义"},
{"word":"option","meaning":"(n.) 选择；选项"},
{"word":"orchestrate","meaning":"(v.) 精心安排；编排"},
{"word":"orient","meaning":"(v.) 定向；适应"},
{"word":"origin","meaning":"(n.) 起源；出身"},
{"word":"original","meaning":"(adj.) 原始的；独创的"},
{"word":"originate","meaning":"(v.) 起源；发起"},
{"word":"outbreak","meaning":"(n.) 爆发；突然发生"},
{"word":"outcome","meaning":"(n.) 结果；成果"},
{"word":"outdoor","meaning":"(adj.) 户外的；室外的"},
{"word":"outpace","meaning":"(v.) 超过；比…跑得快"},
{"word":"outreach","meaning":"(v.) 超出；延伸 (n.) 外展服务"},
{"word":"outset","meaning":"(n.) 开始；开端"},
{"word":"outstanding","meaning":"(adj.) 杰出的；未解决的"},
{"word":"overcome","meaning":"(v.) 克服；战胜"},
{"word":"overlook","meaning":"(v.) 忽视；俯瞰"},
{"word":"overwhelm","meaning":"(v.) 压倒；淹没"},
{"word":"overwhelming","meaning":"(adj.) 压倒性的；势不可挡的"},
{"word":"owe","meaning":"(v.) 欠；归功于"},
{"word":"pace","meaning":"(n.) 步伐；速度 (v.) 踱步"},
{"word":"paradox","meaning":"(n.) 悖论；矛盾"},
{"word":"parallel","meaning":"(adj.) 平行的 (n.) 平行线；相似处"},
{"word":"paralyze","meaning":"(v.) 使瘫痪；使麻痹"},
{"word":"parasites","meaning":"(n.) 寄生虫；食客"},
{"word":"particles","meaning":"(n.) 颗粒；微粒"},
{"word":"particular","meaning":"(adj.) 特定的；特别的"},
{"word":"passion","meaning":"(n.) 激情；热情"},
{"word":"patterns","meaning":"(n.) 模式；图案"},
{"word":"peak","meaning":"(n.) 顶峰；高峰"},
{"word":"peacefully","meaning":"(adv.) 和平地；宁静地"},
{"word":"peculiar","meaning":"(adj.) 奇怪的；特有的"},
{"word":"penalty","meaning":"(n.) 处罚；罚款"},
{"word":"penetrate","meaning":"(v.) 穿透；渗透"},
{"word":"pension","meaning":"(n.) 养老金；退休金"},
{"word":"perceive","meaning":"(v.) 察觉；理解"},
{"word":"permanent","meaning":"(adj.) 永久的；持久的"},
{"word":"permeate","meaning":"(v.) 渗透；弥漫"},
{"word":"permit","meaning":"(v.) 允许 (n.) 许可证"},
{"word":"perpetual","meaning":"(adj.) 永久的；不断的"},
{"word":"perplex","meaning":"(v.) 使困惑；使复杂化"},
{"word":"persist","meaning":"(v.) 坚持；持续"},
{"word":"persistent","meaning":"(adj.) 坚持的；持续的"},
{"word":"perspective","meaning":"(n.) 视角；观点"},
{"word":"persuade","meaning":"(v.) 说服；劝说"},
{"word":"petition","meaning":"(n.) 请愿书 (v.) 请愿"},
{"word":"petroleum","meaning":"(n.) 石油"},
{"word":"phenomenon","meaning":"(n.) 现象；奇迹"},
{"word":"philosophy","meaning":"(n.) 哲学"},
{"word":"physical","meaning":"(adj.) 身体的；物理的"},
{"word":"pioneer","meaning":"(n.) 先驱 (v.) 开辟"},
{"word":"plague","meaning":"(n.) 瘟疫 (v.) 折磨"},
{"word":"plausible","meaning":"(adj.) 似乎合理的"},
{"word":"plead","meaning":"(v.) 恳求；申辩"},
{"word":"pledge","meaning":"(v./n.) 保证；发誓"},
{"word":"plunge","meaning":"(v.) 投入；骤降 (n.) 跳水"},
{"word":"poisonous","meaning":"(adj.) 有毒的；恶毒的"},
{"word":"poll","meaning":"(n.) 民意调查 (v.) 投票"},
{"word":"pollute","meaning":"(v.) 污染"},
{"word":"ponder","meaning":"(v.) 沉思；考虑"},
{"word":"popular","meaning":"(adj.) 流行的；受欢迎的"},
{"word":"populate","meaning":"(v.) 居住于；填充"},
{"word":"portable","meaning":"(adj.) 便携的"},
{"word":"portion","meaning":"(n.) 部分；一份"},
{"word":"portray","meaning":"(v.) 描绘；扮演"},
{"word":"pose","meaning":"(v.) 造成；摆姿势 (n.) 姿势"},
{"word":"positive","meaning":"(adj.) 积极的；肯定的"},
{"word":"possess","meaning":"(v.) 拥有；具有"},
{"word":"postpone","meaning":"(v.) 推迟；延期"},
{"word":"potential","meaning":"(adj.) 潜在的 (n.) 潜力"},
{"word":"poverty","meaning":"(n.) 贫困；贫穷"},
{"word":"practitioner","meaning":"(n.) 从业者；实践者"},
{"word":"preach","meaning":"(v.) 布道；说教"},
{"word":"precaution","meaning":"(n.) 预防措施"},
{"word":"precede","meaning":"(v.) 在…之前；先于"},
{"word":"precedent","meaning":"(n.) 先例；前例"},
{"word":"precious","meaning":"(adj.) 珍贵的；宝贵的"},
{"word":"precise","meaning":"(adj.) 精确的；准确的"},
{"word":"predict","meaning":"(v.) 预测；预言"},
{"word":"predominant","meaning":"(adj.) 占主导地位的；显著的"},
{"word":"predominate","meaning":"(v.) 占主导地位；占优势"},
{"word":"prejudice","meaning":"(n.) 偏见 (v.) 使有偏见"},
{"word":"preliminary","meaning":"(adj.) 初步的；预备的"},
{"word":"premise","meaning":"(n.) 前提；假设"},
{"word":"premium","meaning":"(n.) 保险费；额外费用 (adj.) 优质的"},
{"word":"prescribe","meaning":"(v.) 规定；开处方"},
{"word":"preservation","meaning":"(n.) 保存；保护"},
{"word":"preside","meaning":"(v.) 主持；主导"},
{"word":"prestige","meaning":"(n.) 声望；威信"},
{"word":"presume","meaning":"(v.) 假定；推测"},
{"word":"prevail","meaning":"(v.) 盛行；获胜"},
{"word":"prevalent","meaning":"(adj.) 流行的；普遍的"},
{"word":"prevent","meaning":"(v.) 阻止；预防"},
{"word":"primitive","meaning":"(adj.) 原始的；简陋的"},
{"word":"principal","meaning":"(adj.) 主要的 (n.) 校长；本金"},
{"word":"principle","meaning":"(n.) 原则；原理"},
{"word":"priority","meaning":"(n.) 优先权；重点"},
{"word":"privilege","meaning":"(n.) 特权 (v.) 给予特权"},
{"word":"probe","meaning":"(v.) 探查 (n.) 探针"},
{"word":"proceed","meaning":"(v.) 继续进行；开始"},
{"word":"process","meaning":"(n.) 过程 (v.) 处理"},
{"word":"proclaim","meaning":"(v.) 宣告；声明"},
{"word":"productive","meaning":"(adj.) 多产的；富有成效的"},
{"word":"profession","meaning":"(n.) 职业；专业"},
{"word":"proficient","meaning":"(adj.) 熟练的；精通的"},
{"word":"profile","meaning":"(n.) 侧面；简介"},
{"word":"profound","meaning":"(adj.) 深刻的；深远的"},
{"word":"progressive","meaning":"(adj.) 进步的；渐进的"},
{"word":"prohibit","meaning":"(v.) 禁止；阻止"},
{"word":"project","meaning":"(n.) 项目 (v.) 投射；规划"},
{"word":"prolong","meaning":"(v.) 延长；拖延"},
{"word":"prominent","meaning":"(adj.) 杰出的；显著的"},
{"word":"promote","meaning":"(v.) 促进；晋升；推广"},
{"word":"prompt","meaning":"(v.) 促使 (adj.) 迅速的"},
{"word":"prone","meaning":"(adj.) 易于…的；俯卧的"},
{"word":"proportion","meaning":"(n.) 比例；部分"},
{"word":"propose","meaning":"(v.) 提议；建议"},
{"word":"prospect","meaning":"(n.) 前景；可能性"},
{"word":"prosperity","meaning":"(n.) 繁荣；兴旺"},
{"word":"prosperous","meaning":"(adj.) 繁荣的；兴旺的"},
{"word":"protest","meaning":"(v./n.) 抗议；反对"},
{"word":"provision","meaning":"(n.) 供应；规定；条款"},
{"word":"provoke","meaning":"(v.) 激怒；引起"},
{"word":"prudent","meaning":"(adj.) 谨慎的；审慎的"},
{"word":"psychological","meaning":"(adj.) 心理的；心理学的"},
{"word":"publicity","meaning":"(n.) 宣传；公众注意"},
{"word":"punish","meaning":"(v.) 惩罚；处罚"},
{"word":"purchase","meaning":"(v.) 购买 (n.) 购买物"},
{"word":"pursue","meaning":"(v.) 追求；追赶"},
{"word":"puzzle","meaning":"(v.) 使困惑 (n.) 谜"},
{"word":"qualify","meaning":"(v.) 使合格；限定"},
{"word":"quantitative","meaning":"(adj.) 定量的；数量的"},
{"word":"quench","meaning":"(v.) 解渴；扑灭"},
{"word":"quest","meaning":"(n.) 探索；追求"},
{"word":"radiating","meaning":"(v.) 辐射；散发"},
{"word":"rage","meaning":"(n.) 愤怒"},
{"word":"raising","meaning":"(v.) 举起；提高；抚养"},
{"word":"random","meaning":"(adj.) 随机的；任意的"},
{"word":"rapidly","meaning":"(adv.) 迅速地"},
{"word":"rarely","meaning":"(adv.) 很少；难得"},
{"word":"ration","meaning":"(n.) 定量；配给 (v.) 定量供应"},
{"word":"rational","meaning":"(adj.) 理性的；合理的"},
{"word":"realm","meaning":"(n.) 领域；王国"},
{"word":"reap","meaning":"(v.) 收割；获得"},
{"word":"reasonable","meaning":"(adj.) 合理的；公道的"},
{"word":"rebel","meaning":"(v.) 反叛 (n.) 叛逆者"},
{"word":"recall","meaning":"(v.) 回忆；召回 (n.) 回忆"},
{"word":"recession","meaning":"(n.) 衰退；不景气"},
{"word":"recipient","meaning":"(n.) 接受者；收件人"},
{"word":"recite","meaning":"(v.) 背诵；朗诵"},
{"word":"reckless","meaning":"(adj.) 鲁莽的；不顾后果的"},
{"word":"reckon","meaning":"(v.) 认为；估算"},
{"word":"reconcile","meaning":"(v.) 调和；使和解"},
{"word":"reconstruction","meaning":"(n.) 重建；改造"},
{"word":"recover","meaning":"(v.) 恢复；找回"},
{"word":"recruit","meaning":"(v.) 招募 (n.) 新兵"},
{"word":"recur","meaning":"(v.) 再发生；重现"},
{"word":"recycle","meaning":"(v.) 回收利用"},
{"word":"reduce","meaning":"(v.) 减少；降低"},
{"word":"redundant","meaning":"(adj.) 多余的；冗余的"},
{"word":"refer","meaning":"(v.) 提到；参考"},
{"word":"refine","meaning":"(v.) 精炼；改进"},
{"word":"reflect","meaning":"(v.) 反映；反射；反思"},
{"word":"reform","meaning":"(v./n.) 改革；改良"},
{"word":"refrain","meaning":"(v.) 克制；避免"},
{"word":"refresh","meaning":"(v.) 使恢复；刷新"},
{"word":"refuge","meaning":"(n.) 避难；庇护"},
{"word":"refund","meaning":"(n.) 退款 (v.) 退还"},
{"word":"refute","meaning":"(v.) 反驳；驳斥"},
{"word":"regarding","meaning":"(prep.) 关于；至于"},
{"word":"regime","meaning":"(n.) 政权；体制"},
{"word":"region","meaning":"(n.) 地区；区域"},
{"word":"register","meaning":"(v.) 注册；登记 (n.) 登记表"},
{"word":"regulate","meaning":"(v.) 管理；调节"},
{"word":"rehabilitate","meaning":"(v.) 使康复；修复"},
{"word":"reinforce","meaning":"(v.) 加强；增援"},
{"word":"reject","meaning":"(v.) 拒绝；排斥"},
{"word":"relate","meaning":"(v.) 联系；叙述"},
{"word":"release","meaning":"(v.) 释放；发布 (n.) 释放"},
{"word":"relevant","meaning":"(adj.) 相关的；切题的"},
{"word":"reliable","meaning":"(adj.) 可靠的"},
{"word":"relic","meaning":"(n.) 遗迹；遗物"},
{"word":"relief","meaning":"(n.) 缓解；救济"},
{"word":"reluctant","meaning":"(adj.) 不情愿的；勉强的"},
{"word":"rely","meaning":"(v.) 依赖；信赖"},
{"word":"remain","meaning":"(v.) 保持；剩余"},
{"word":"remarkable","meaning":"(adj.) 显著的；非凡的"},
{"word":"remedy","meaning":"(n.) 补救办法 (v.) 纠正"},
{"word":"remit","meaning":"(v.) 汇款；免除"},
{"word":"remnant","meaning":"(n.) 残余；遗迹"},
{"word":"remote","meaning":"(adj.) 遥远的；偏僻的"},
{"word":"render","meaning":"(v.) 使成为；给予"},
{"word":"renew","meaning":"(v.) 更新；续期"},
{"word":"renowned","meaning":"(adj.) 著名的"},
{"word":"rental","meaning":"(n.) 租金 (adj.) 出租的"},
{"word":"repay","meaning":"(v.) 偿还；报答"},
{"word":"repeal","meaning":"(v./n.) 废除；撤销"},
{"word":"reproduce","meaning":"(v.) 繁殖；复制"},
{"word":"republic","meaning":"(n.) 共和国"},
{"word":"reputation","meaning":"(n.) 名声；声誉"},
{"word":"request","meaning":"(v./n.) 请求；要求"},
{"word":"require","meaning":"(v.) 需要；要求"},
{"word":"resemble","meaning":"(v.) 类似；像"},
{"word":"resent","meaning":"(v.) 怨恨；愤恨"},
{"word":"reserve","meaning":"(v.) 预订；保留 (n.) 储备"},
{"word":"reside","meaning":"(v.) 居住；存在"},
{"word":"resident","meaning":"(n.) 居民 (adj.) 居住的"},
{"word":"resign","meaning":"(v.) 辞职；放弃"},
{"word":"resist","meaning":"(v.) 抵抗；抵制"},
{"word":"resolute","meaning":"(adj.) 坚决的；果断的"},
{"word":"resolve","meaning":"(v.) 解决；决心 (n.) 决心"},
{"word":"resort","meaning":"(v.) 诉诸 (n.) 度假胜地"},
{"word":"resource","meaning":"(n.) 资源；财力"},
{"word":"respond","meaning":"(v.) 回应；反应"},
{"word":"restore","meaning":"(v.) 恢复；修复"},
{"word":"restrain","meaning":"(v.) 抑制；约束"},
{"word":"restrict","meaning":"(v.) 限制；约束"},
{"word":"retain","meaning":"(v.) 保留；保持"},
{"word":"retreat","meaning":"(v./n.) 撤退；退却"},
{"word":"retrieve","meaning":"(v.) 取回；检索"},
{"word":"reveal","meaning":"(v.) 揭示；显示"},
{"word":"revenue","meaning":"(n.) 收入；税收"},
{"word":"reverse","meaning":"(v.) 颠倒；反转 (adj.) 相反的"},
{"word":"revise","meaning":"(v.) 修改；复习"},
{"word":"revive","meaning":"(v.) 复苏；恢复"},
{"word":"revolve","meaning":"(v.) 旋转；围绕"},
{"word":"rival","meaning":"(n.) 对手 (v.) 竞争"},
{"word":"robust","meaning":"(adj.) 强健的；稳健的"},
{"word":"routine","meaning":"(n.) 常规 (adj.) 日常的"},
{"word":"rubbish","meaning":"(n.) 垃圾；废话"},
{"word":"rude","meaning":"(adj.) 粗鲁的；无礼的"},
{"word":"rural","meaning":"(adj.) 农村的；乡下的"},
{"word":"sacred","meaning":"(adj.) 神圣的；宗教的"},
{"word":"sacrifice","meaning":"(v./n.) 牺牲；献祭"},
{"word":"safeguarded","meaning":"(v.) 保护；维护"},
{"word":"safeguarding","meaning":"(v.) 保护；维护"},
{"word":"saturated","meaning":"(adj.) 饱和的；湿透的"},
{"word":"scale","meaning":"(n.) 规模；等级；鳞片"},
{"word":"scenario","meaning":"(n.) 设想；方案；场景"},
{"word":"scenarios","meaning":"(n.) 设想；方案 (复数)"},
{"word":"skeptical","meaning":"(adj.) 怀疑的"},
{"word":"scatter","meaning":"(v.) 散开；撒播"},
{"word":"schedule","meaning":"(n.) 时间表 (v.) 安排"},
{"word":"scheme","meaning":"(n.) 计划；方案 (v.) 策划"},
{"word":"scope","meaning":"(n.) 范围；机会"},
{"word":"scrutiny","meaning":"(n.) 审查；细看"},
{"word":"secure","meaning":"(adj.) 安全的 (v.) 获得；保护"},
{"word":"segregate","meaning":"(v.) 隔离；分离"},
{"word":"seize","meaning":"(v.) 抓住；夺取"},
{"word":"selective","meaning":"(adj.) 选择性的；挑剔的"},
{"word":"sensation","meaning":"(n.) 感觉；轰动"},
{"word":"sensitive","meaning":"(adj.) 敏感的；灵敏的"},
{"word":"sequence","meaning":"(n.) 顺序；连续"},
{"word":"session","meaning":"(n.) 会议；一段时间"},
{"word":"setback","meaning":"(n.) 挫折；倒退"},
{"word":"shatter","meaning":"(v.) 粉碎；破坏"},
{"word":"shed","meaning":"(v.) 流出；脱落 (n.) 棚屋"},
{"word":"shelter","meaning":"(n.) 避难所 (v.) 庇护"},
{"word":"shift","meaning":"(v.) 转移；改变 (n.) 转变"},
{"word":"shortage","meaning":"(n.) 短缺；不足"},
{"word":"shrink","meaning":"(v.) 收缩；缩小"},
{"word":"signal","meaning":"(n.) 信号 (v.) 发信号"},
{"word":"significant","meaning":"(adj.) 重要的；显著的"},
{"word":"simplify","meaning":"(v.) 简化"},
{"word":"simulate","meaning":"(v.) 模拟；模仿"},
{"word":"simultaneous","meaning":"(adj.) 同时的"},
{"word":"sincere","meaning":"(adj.) 真诚的；诚挚的"},
{"word":"situated","meaning":"(adj.) 位于…的"},
{"word":"skeptical","meaning":"(adj.) 怀疑的"},
{"word":"slash","meaning":"(v.) 大幅削减；砍"},
{"word":"slaughter","meaning":"(v./n.) 屠杀；屠宰"},
{"word":"slight","meaning":"(adj.) 轻微的；微小的"},
{"word":"slim","meaning":"(adj.) 苗条的；微小的"},
{"word":"slump","meaning":"(v.) 暴跌；萧条 (n.) 萧条期"},
{"word":"smash","meaning":"(v.) 粉碎；猛撞"},
{"word":"soar","meaning":"(v.) 猛增；翱翔"},
{"word":"sober","meaning":"(adj.) 清醒的；严肃的"},
{"word":"sociable","meaning":"(adj.) 好交际的；友善的"},
{"word":"sophisticated","meaning":"(adj.) 复杂的；老练的"},
{"word":"source","meaning":"(n.) 来源；源泉"},
{"word":"span","meaning":"(n.) 跨度；期间 (v.) 横跨"},
{"word":"spark","meaning":"(n.) 火花 (v.) 引发"},
{"word":"specify","meaning":"(v.) 具体说明；指定"},
{"word":"specimen","meaning":"(n.) 标本；样本"},
{"word":"spectacle","meaning":"(n.) 景象；奇观"},
{"word":"spectacular","meaning":"(adj.) 壮观的；惊人的"},
{"word":"speculate","meaning":"(v.) 推测；投机"},
{"word":"sphere","meaning":"(n.) 球体；领域"},
{"word":"spiral","meaning":"(n.) 螺旋 (adj.) 螺旋的 (v.) 盘旋"},
{"word":"spontaneous","meaning":"(adj.) 自发的；自然的"},
{"word":"stability","meaning":"(n.) 稳定性"},
{"word":"stagnant","meaning":"(adj.) 停滞的；不景气的"},
{"word":"stake","meaning":"(n.) 赌注；股份 (v.) 打赌"},
{"word":"stale","meaning":"(adj.) 不新鲜的；陈腐的"},
{"word":"stamina","meaning":"(n.) 耐力；体力"},
{"word":"standard","meaning":"(n.) 标准 (adj.) 标准的"},
{"word":"staple","meaning":"(n.) 主食；主要产品 (adj.) 主要的"},
{"word":"startling","meaning":"(adj.) 令人吃惊的"},
{"word":"starve","meaning":"(v.) 挨饿；渴望"},
{"word":"static","meaning":"(adj.) 静态的；停滞的"},
{"word":"statistical","meaning":"(adj.) 统计的；统计学的"},
{"word":"status","meaning":"(n.) 地位；状态"},
{"word":"steady","meaning":"(adj.) 稳定的；平稳的"},
{"word":"steer","meaning":"(v.) 驾驶；引导"},
{"word":"stem","meaning":"(n.) 茎；词干 (v.) 起源"},
{"word":"stereotype","meaning":"(n.) 刻板印象 (v.) 对…形成刻板印象"},
{"word":"stiff","meaning":"(adj.) 僵硬的；严厉的"},
{"word":"stimulate","meaning":"(v.) 刺激；激励"},
{"word":"sting","meaning":"(v.) 刺；叮 (n.) 刺痛"},
{"word":"stir","meaning":"(v.) 搅动；激起 (n.) 搅动"},
{"word":"strain","meaning":"(n.) 压力；菌株 (v.) 拉紧"},
{"word":"strand","meaning":"(n.) 股；线 (v.) 使搁浅"},
{"word":"strategy","meaning":"(n.) 策略；战略"},
{"word":"strengthen","meaning":"(v.) 加强；巩固"},
{"word":"stress","meaning":"(n.) 压力；强调 (v.) 强调"},
{"word":"stretch","meaning":"(v.) 伸展；延伸 (n.) 伸展"},
{"word":"strict","meaning":"(adj.) 严格的；严厉的"},
{"word":"stride","meaning":"(v.) 大步走 (n.) 大步；进展"},
{"word":"strike","meaning":"(v.) 罢工；打击 (n.) 罢工"},
{"word":"stringent","meaning":"(adj.) 严格的；严厉的"},
{"word":"strip","meaning":"(v.) 剥去 (n.) 条；带"},
{"word":"strive","meaning":"(v.) 努力；奋斗"},
{"word":"stroke","meaning":"(n.) 中风；击打 (v.) 抚摸"},
{"word":"structure","meaning":"(n.) 结构；建筑 (v.) 组织"},
{"word":"stubborn","meaning":"(adj.) 固执的；顽强的"},
{"word":"stumble","meaning":"(v.) 绊倒；犯错"},
{"word":"stun","meaning":"(v.) 使震惊；击晕"},
{"word":"sturdy","meaning":"(adj.) 坚固的；强壮的"},
{"word":"subject","meaning":"(n.) 主题；科目 (adj.) 易受…的 (v.) 使服从"},
{"word":"submerge","meaning":"(v.) 淹没；潜入水中"},
{"word":"submit","meaning":"(v.) 提交；服从"},
{"word":"subordinate","meaning":"(adj.) 下级的；次要的 (n.) 下属"},
{"word":"subscribe","meaning":"(v.) 订阅；同意"},
{"word":"subsequent","meaning":"(adj.) 随后的；后来的"},
{"word":"subsidy","meaning":"(n.) 补贴；津贴"},
{"word":"substance","meaning":"(n.) 物质；实质"},
{"word":"substantial","meaning":"(adj.) 大量的；实质性的"},
{"word":"substitute","meaning":"(v.) 替代 (n.) 替代品"},
{"word":"subtle","meaning":"(adj.) 微妙的；精巧的"},
{"word":"subtract","meaning":"(v.) 减去；扣除"},
{"word":"suburb","meaning":"(n.) 郊区"},
{"word":"succession","meaning":"(n.) 连续；继承"},
{"word":"successive","meaning":"(adj.) 连续的；继承的"},
{"word":"succinct","meaning":"(adj.) 简明的；简洁的"},
{"word":"sue","meaning":"(v.) 起诉；控告"},
{"word":"sufficient","meaning":"(adj.) 足够的；充分的"},
{"word":"summon","meaning":"(v.) 召唤；召集"},
{"word":"superficial","meaning":"(adj.) 表面的；肤浅的"},
{"word":"superior","meaning":"(adj.) 优越的 (n.) 上级"},
{"word":"supplement","meaning":"(n.) 补充 (v.) 增补"},
{"word":"suppress","meaning":"(v.) 镇压；抑制"},
{"word":"supreme","meaning":"(adj.) 最高的；至上的"},
{"word":"surge","meaning":"(v./n.) 激增；汹涌"},
{"word":"surplus","meaning":"(n.) 剩余；盈余 (adj.) 剩余的"},
{"word":"surrender","meaning":"(v./n.) 投降；放弃"},
{"word":"surveillance","meaning":"(n.) 监视；监控"},
{"word":"survey","meaning":"(n.) 调查 (v.) 调查；审视"},
{"word":"survive","meaning":"(v.) 幸存；存活"},
{"word":"susceptible","meaning":"(adj.) 易受影响的；敏感的"},
{"word":"suspect","meaning":"(v.) 怀疑 (n.) 嫌疑犯"},
{"word":"suspend","meaning":"(v.) 暂停；悬挂"},
{"word":"sustain","meaning":"(v.) 维持；承受"},
{"word":"sustainable","meaning":"(adj.) 可持续的"},
{"word":"swallow","meaning":"(v.) 吞咽；轻信 (n.) 燕子"},
{"word":"swamp","meaning":"(n.) 沼泽 (v.) 淹没"},
{"word":"sweep","meaning":"(v.) 扫；席卷 (n.) 扫除"},
{"word":"swell","meaning":"(v.) 膨胀；增加 (n.) 膨胀"},
{"word":"switch","meaning":"(v.) 转换 (n.) 开关"},
{"word":"symbolic","meaning":"(adj.) 象征的；符号的"},
{"word":"sympathy","meaning":"(n.) 同情；赞同"},
{"word":"symptom","meaning":"(n.) 症状；征兆"},
{"word":"synchronize","meaning":"(v.) 使同步；使协调"},
{"word":"synthetic","meaning":"(adj.) 合成的；人造的"},
{"word":"tackle","meaning":"(v.) 处理；对付 (n.) 用具"},
{"word":"tailor","meaning":"(n.) 裁缝 (v.) 量身定制"},
{"word":"target","meaning":"(n.) 目标；靶子 (v.) 把…作为目标"},
{"word":"temperament","meaning":"(n.) 气质；性情"},
{"word":"tempt","meaning":"(v.) 引诱；吸引"},
{"word":"temptations","meaning":"(n.) 诱惑；诱惑物 (复数)"},
{"word":"tempting","meaning":"(adj.) 诱人的；吸引人的"},
{"word":"tenured","meaning":"(adj.) 享有终身职位的"},
{"word":"terminate","meaning":"(v.) (使)终止；结束"},
{"word":"terrain","meaning":"(n.) 地形；地势"},
{"word":"terrific","meaning":"(adj.) 极好的；非常大的"},
{"word":"terrify","meaning":"(v.) 使恐惧；使害怕"},
{"word":"territory","meaning":"(n.) 领土；领域"},
{"word":"testify","meaning":"(v.) 作证；证明"},
{"word":"testimony","meaning":"(n.) 证词；证据"},
{"word":"texture","meaning":"(n.) 质地；纹理"},
{"word":"thankful","meaning":"(adj.) 感谢的；欣慰的"},
{"word":"theft","meaning":"(n.) 偷窃；盗窃"},
{"word":"theme","meaning":"(n.) 主题；主旨"},
{"word":"therapy","meaning":"(n.) 治疗；疗法"},
{"word":"thereby","meaning":"(adv.) 因此；从而"},
{"word":"thesis","meaning":"(n.) 论文；论点"},
{"word":"thorough","meaning":"(adj.) 彻底的；详尽的"},
{"word":"threat","meaning":"(n.) 威胁；恐吓"},
{"word":"threshold","meaning":"(n.) 门槛；起点"},
{"word":"thrive","meaning":"(v.) 繁荣；茁壮成长"},
{"word":"thrust","meaning":"(v.) 猛推；刺 (n.) 推力"},
{"word":"tidy","meaning":"(adj.) 整洁的 (v.) 整理"},
{"word":"timber","meaning":"(n.) 木材；木料"},
{"word":"tolerate","meaning":"(v.) 容忍；忍受"},
{"word":"toll","meaning":"(n.) 通行费；伤亡人数"},
{"word":"topic","meaning":"(n.) 话题；主题"},
{"word":"torture","meaning":"(v./n.) 折磨；拷问"},
{"word":"toss","meaning":"(v.) 抛；掷 (n.) 抛"},
{"word":"trace","meaning":"(v.) 追踪 (n.) 痕迹；微量"},
{"word":"trademark","meaning":"(n.) 商标；特征"},
{"word":"tradition","meaning":"(n.) 传统；惯例"},
{"word":"tragic","meaning":"(adj.) 悲惨的；悲剧的"},
{"word":"trail","meaning":"(n.) 小径；痕迹 (v.) 跟踪"},
{"word":"trait","meaning":"(n.) 特征；特点"},
{"word":"transaction","meaning":"(n.) 交易；事务"},
{"word":"transcend","meaning":"(v.) 超越；胜过"},
{"word":"transfer","meaning":"(v.) 转移；转让 (n.) 转移"},
{"word":"transform","meaning":"(v.) 改变；转变"},
{"word":"transient","meaning":"(adj.) 短暂的；临时的"},
{"word":"transition","meaning":"(n.) 过渡；转变"},
{"word":"translate","meaning":"(v.) 翻译；转化"},
{"word":"transmit","meaning":"(v.) 传输；传播"},
{"word":"transparent","meaning":"(adj.) 透明的；坦率的"},
{"word":"transplant","meaning":"(v.) 移植 (n.) 移植"},
{"word":"trauma","meaning":"(n.) 创伤；外伤"},
{"word":"treasure","meaning":"(n.) 财宝 (v.) 珍视"},
{"word":"tremendous","meaning":"(adj.) 巨大的；极大的"},
{"word":"trend","meaning":"(n.) 趋势；倾向"},
{"word":"tribe","meaning":"(n.) 部落；族"},
{"word":"trigger","meaning":"(v.) 触发；引起 (n.) 扳机"},
{"word":"triumph","meaning":"(n.) 胜利 (v.) 获胜"},
{"word":"trivial","meaning":"(adj.) 琐碎的；微不足道的"},
{"word":"tropical","meaning":"(adj.) 热带的"},
{"word":"trust","meaning":"(n.) 信任 (v.) 信任"},
{"word":"turbulent","meaning":"(adj.) 动荡的；混乱的"},
{"word":"twist","meaning":"(v.) 扭转；扭曲 (n.) 转折"},
{"word":"typical","meaning":"(adj.) 典型的；有代表性的"},
{"word":"ultimate","meaning":"(adj.) 最终的；根本的"},
{"word":"undergo","meaning":"(v.) 经历；遭受"},
{"word":"underline","meaning":"(v.) 强调；在…下划线"},
{"word":"undermine","meaning":"(v.) 逐渐削弱；损害"},
{"word":"undertake","meaning":"(v.) 承担；从事"},
{"word":"unemployment","meaning":"(n.) 失业"},
{"word":"unfold","meaning":"(v.) 展开；展现"},
{"word":"unify","meaning":"(v.) 统一；使一致"},
{"word":"unique","meaning":"(adj.) 独特的；唯一的"},
{"word":"universal","meaning":"(adj.) 普遍的；全世界的"},
{"word":"unprecedented","meaning":"(adj.) 前所未有的"},
{"word":"unveil","meaning":"(v.) 揭幕；公布"},
{"word":"upgrade","meaning":"(v.) 升级 (n.) 升级"},
{"word":"uphold","meaning":"(v.) 支持；维护"},
{"word":"upright","meaning":"(adj.) 直立的；正直的"},
{"word":"upset","meaning":"(adj.) 心烦的 (v.) 使心烦；打翻"},
{"word":"urban","meaning":"(adj.) 城市的"},
{"word":"urge","meaning":"(v.) 催促；强烈要求 (n.) 冲动"},
{"word":"urgent","meaning":"(adj.) 紧急的；迫切的"},
{"word":"utilize","meaning":"(v.) 利用；使用"},
{"word":"utmost","meaning":"(adj.) 最大的；极度的 (n.) 极限"},
{"word":"vacant","meaning":"(adj.) 空的；空缺的"},
{"word":"vague","meaning":"(adj.) 模糊的；不明确的"},
{"word":"valid","meaning":"(adj.) 有效的；合理的"},
{"word":"vanish","meaning":"(v.) 消失；消散"},
{"word":"variable","meaning":"(adj.) 多变的 (n.) 变量"},
{"word":"variation","meaning":"(n.) 变化；变异"},
{"word":"venture","meaning":"(n.) 风险投资 (v.) 冒险"},
{"word":"verbal","meaning":"(adj.) 口头的；词语的"},
{"word":"verdict","meaning":"(n.) 裁决；判决"},
{"word":"verify","meaning":"(v.) 核实；证实"},
{"word":"versatile","meaning":"(adj.) 多才多艺的；多功能的"},
{"word":"version","meaning":"(n.) 版本；说法"},
{"word":"vertical","meaning":"(adj.) 垂直的"},
{"word":"veto","meaning":"(v./n.) 否决"},
{"word":"viable","meaning":"(adj.) 可行的；能存活的"},
{"word":"vibrant","meaning":"(adj.) 充满活力的；鲜明的"},
{"word":"vicious","meaning":"(adj.) 恶毒的；凶残的"},
{"word":"violate","meaning":"(v.) 违反；侵犯"},
{"word":"virtual","meaning":"(adj.) 虚拟的；实质上的"},
{"word":"virtue","meaning":"(n.) 美德；优点"},
{"word":"visible","meaning":"(adj.) 看得见的；明显的"},
{"word":"vision","meaning":"(n.) 视力；愿景"},
{"word":"vital","meaning":"(adj.) 至关重要的；生命的"},
{"word":"vivid","meaning":"(adj.) 生动的；鲜明的"},
{"word":"vocabulary","meaning":"(n.) 词汇；词汇量"},
{"word":"voluntary","meaning":"(adj.) 自愿的；志愿的"},
{"word":"vulnerable","meaning":"(adj.) 脆弱的；易受伤的"},
{"word":"warrant","meaning":"(v.) 保证；授权 (n.) 许可证"},
{"word":"weave","meaning":"(v.) 编织；编排"},
{"word":"welfare","meaning":"(n.) 福利；幸福"},
{"word":"whereas","meaning":"(conj.) 然而；鉴于"},
{"word":"widespread","meaning":"(adj.) 广泛的；普遍的"},
{"word":"withdrawn","meaning":"(v.) 撤回；退出 (过去分词) (adj.) 孤僻的"},
{"word":"withdraws","meaning":"(v.) 撤回；取款"},
{"word":"worldwide","meaning":"(adj./adv.) 全世界的/地"},
{"word":"wrestle","meaning":"(v.) 摔跤；奋力解决"}
];
